### ISSUE TITLE
Will it work?

### ISSUE THREAD

**Issue by mosbth** [cruzzan/blog-project#1]
Almost.
![image](https://user-images.githubusercontent.com/169550/215342023-6e5e39c9-c355-47ad-853f-9d3a20220401.png)

Hmm, lets see if I can figure it out...

**Comment by mosbth** [comment]
Ok, worked better when I just `docker-compose up -d`. So lets start it. Hmmm.
![image](https://user-images.githubusercontent.com/169550/215342181-894317ed-28c3-473f-ac25-814754085921.png)

**Comment by mosbth** [comment]
Ok, can be fixed with:
```
chmod 777 storage/logs/
```

But then...
![image](https://user-images.githubusercontent.com/169550/215342853-97d9f3bd-aa61-4873-a4e3-0cc5156a2697.png)

**Comment by mosbth** [comment]
Any hint on how to fix the last error?

**Comment by cruzzan** [comment]
@mosbth i see what the original issue is. I am using the naming conventions for the new docker-compose version. `blog-project-site-1` vs `blog-project-site_1`. For some reason they changed from an underscore to a dash, a while back. I'll push a fix for the script.

**Comment by cruzzan** [comment]
Alright, if you pull the latest changes and run the quickstart instructions again, the issue should be fixed. (You might want to run the teardown steps first, in case postgres has gotten to a state that i haven't covered in the startup script.)

Thanks for the great issue submission, it made it very simple to work with the problem :grin:
