### ISSUE TITLE
PORT_TO_USE är hårdkodad i start.sh 

### ISSUE THREAD

**Issue by mosbth** [cruzzan/blog-project#2]
I start.sh https://github.com/cruzzan/blog-project/blob/master/start.sh#L5, ändra:

```
PORT_TO_USE="8080"
```

till

```
PORT_TO_USE="${PORT_TO_USE:-8080}"
```

så kan man starta skriptet med:

```
PORT_TO_USE=8888; ./start.sh 
```

**Comment by cruzzan** [comment]
Yeah, you are completely right!
